version: '3'

services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: admin #superuser権限を持つ指定された名前のユーザーとデータベースを作成します
      POSTGRES_PASSWORD: admin #PostgreSQLのsuper userパスワードを設定
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/work:/usr/src
      - ./database/db:/var/lib/postgresql/data
    ports:
      - "5433:5433" #外部からのアクセス時のポート:dockerコンテナからアクセスする時のポート
    networks:
      my-network:
        ipv4_address: 172.21.238.3
  server:
    build: ./server
    volumes:
      - ./server/work:/home/developer/work:rw
    ports:
      - "8080:8080"
    networks:
      my-network:
        ipv4_address: 172.21.238.2
    tty: true
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.238.0/24